import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: '👋 Introduction',
    },
    {
      type: 'doc',
      id: 'quickstart',
      label: '🚀 Quick Start',
    },
    {
      type: 'category',
      label: '📖 Core Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'activiti-core/activiti-engine',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 API Reference',
      items: [
        'api-reference',
        {
          type: 'category',
          label: 'API Modules',
          items: [
            {
              type: 'autogenerated',
              dirName: 'activiti-api',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ Implementation',
      items: [
        'implementation-patterns',
        'best-practices',
      ],
    },
    {
      type: 'category',
      label: '🔧 Core Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'activiti-core',
        },
      ],
    },
    {
      type: 'category',
      label: '📦 Common Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'activiti-core-common',
        },
      ],
    },
    {
      type: 'doc',
      id: 'troubleshooting',
      label: '🐛 Troubleshooting',
    },
    {
      type: 'doc',
      id: 'changelog',
      label: '📝 Changelog',
    },
  ],
};

export default sidebars;
